spring:
  application:
    name: hhp5_ca
  datasource:
    url: jdbc:h2:~/lec
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true